apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "am-pattern-1.resource.prefix" . }}-am-gateway-ingress
  namespace: {{ .Release.Namespace }}
{{- if .Values.wso2.deployment.am.ingress.gateway.annotations }}
  annotations:
{{ toYaml .Values.wso2.deployment.am.ingress.gateway.annotations | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.wso2.deployment.am.ingress.gateway.hostname }}
  rules:
    - host: {{ .Values.wso2.deployment.am.ingress.gateway.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "am-pattern-1.resource.prefix" . }}-am-service
                port:
                  number: 8243

